// client/myapp/src/routes/login/+page.svelte
<svelte:head>
	<title>Login</title>
	<meta name="description" content="Login page" />
</svelte:head>

<script>
  import {redirect} from '@sveltejs/kit'
  export let form

  if (form) {
    redirect(303, '/')
  }
</script>

<div class="container">
  <div class="row justify-content-center">

    <div class="col-lg-7">

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <div class="row">
            <div class="col-lg">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Sign in</h1>
                </div>

                  <form method="POST">
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>

                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="password" name="password" placeholder="Password">
                    </div>

                    <button type="submit" class="btn btn-primary">Login</button>
                  </form>

                <div class="text-center">
                  <a class="small" href="/register">Create an Account!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>

// client/src/components/Login.vue
<template>
  <layout-div>
       <div class="row justify-content-md-center mt-5">
           <div class="col-4">
               <div class="card">
                   <div class="card-body">
                       <h5 class="card-title mb-4">Sign In</h5>
                       <form>
                           <p v-if="Object.keys(validationErrors).length != 0" class='text-center '><small class='text-danger'>Incorrect Email or Password</small></p>
                           <div class="mb-3">
                               <label 
                                   htmlFor="email"
                                   class="form-label">
                                       Email address
                               </label>
                               <input 
                                   v-model="email"
                                   type="email"
                                   class="form-control"
                                   id="email"
                                   name="email"
                               />
                           </div>
                           <div class="mb-3">
                               <label 
                                   htmlFor="password"
                                   class="form-label">Password
                               </label>
                               <input 
                                   v-model="password"
                                   type="password"
                                   class="form-control"
                                   id="password"
                                   name="password"
                               />
                           </div>
                           <div class="d-grid gap-2">
                               <button 
                                   :disabled="isSubmitting"
                                   @click="loginAction()"
                                   type="submit"
                                   class="btn btn-primary btn-block">Login</button>
                               <p class="text-center">Don't have account? 
                                   <router-link to="/register">Register here </router-link>
                               </p>
                           </div>
                       </form>
                   </div>
               </div>
           </div>
       </div>
        
  </layout-div>
</template>
 
<script>
import axios from 'axios';
import LayoutDiv from './LayoutDiv.vue';
 
export default {
 name: 'LoginPage',
 components: {
   LayoutDiv,
 },
 data() {
   return {
       email:'',
       password:'',
       validationErrors:{},
       isSubmitting:false,
   };
 },
 created() {
   if(localStorage.getItem('token') != "" && localStorage.getItem('token') != null){
       this.$router.push('/dashboard')
   }
 },
 methods: {
    loginAction(){
       this.isSubmitting = true
       let payload = {
           email: this.email,
           password: this.password,
       }
       axios.post('http://localhost:8000/api/v1/login', payload)
         .then(response => {
           localStorage.setItem('token', response.data.token)
           this.$router.push('/dashboard')
           return response
         })
         .catch(error => {
           this.isSubmitting = false
          if (error.response.data.errors != undefined) {
               this.validationErrors = error.response.data.errors
           }
           if (error.response.data.error != undefined) {
               this.validationErrors = error.response.data.error
           }
           return error
         });
    }
 },
};
</script>
