// client/myapp/src/routes/register/+page.svelte
<svelte:head>
	<title>Login</title>
	<meta name="description" content="Login page" />
</svelte:head>

<script>
  export let form
</script>

<div class="container">
  <div class="row justify-content-center">

    <div class="col-lg-7">

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <div class="row">
            <div class="col-lg">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Sign in</h1>
                </div>

                  <form method="POST">
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="name" name="name" aria-describedby="emailHelp" placeholder="Enter username">
                    </div>

                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter Email Address">
                    </div>

                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="password" name="password" placeholder="Password">
                    </div>

                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="password_confirmation" name="password_confirmation" placeholder="Password Confirmation">
                    </div>

                    <button type="submit" class="btn btn-primary">Register</button>
                  </form>

                  {#if form?.error}
                    <p class="alert alert-danger">{form.error}</p>
                  {/if}

                <div class="text-center">
                  <a class="small" href="/login">Already have an Account!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>

// client/src/components/Register.vue
<template>
  <layout-div>
      <div class="row justify-content-md-center mt-5">
           <div class="col-4">
               <div class="card">
                   <div class="card-body">
                       <h5 class="card-title mb-4">Register</h5>
                       <form >
                           <div class="mb-3">
                               <label 
                                   htmlFor="name"
                                   class="form-label">Name
                               </label>
                               <input 
                                   type="text"
                                   class="form-control"
                                   id="name"
                                   name="name"
                                   v-model="name"
                               />
                               <div v-if="validationErrors.name" class="flex flex-col">
                                   <small  class="text-danger">
                                   {{validationErrors?.name[0]}}
                                   </small >
                               </div>      
                           </div>
                           <div class="mb-3">
                               <label 
                                   htmlFor="email"
                                   class="form-label">Email address
                               </label>
                               <input 
                                   type="email"
                                   class="form-control"
                                   id="email"
                                   name="email"
                                   v-model="email"
                               />
                               <div v-if="validationErrors.email" class="flex flex-col">
                                   <small  class="text-danger">
                                   {{validationErrors?.email[0]}}
                                   </small >
                               </div>
                           </div>
                           <div class="mb-3">
                               <label 
                                   htmlFor="password"
                                   class="form-label">Password
                               </label>
                               <input 
                                   type="password"
                                   class="form-control"
                                   id="password"
                                   name="password"
                                   v-model="password"
                               />
                              <div v-if="validationErrors.password" class="flex flex-col">
                                   <small  class="text-danger">
                                   {{validationErrors?.password[0]}}
                                   </small >
                               </div>
                           </div>
                           <div class="mb-3">
                               <label 
                                   htmlFor="confirm_password"
                                   class="form-label">Confirm Password
                               </label>
                               <input 
                                   type="password"
                                   class="form-control"
                                   id="confirm_password"
                                   name="confirm_password"
                                   v-model="confirmPassword"
                               />
                           </div>
                           <div class="d-grid gap-2">
                               <button 
                                   :disabled="isSubmitting"
                                   @click="registerAction()"
                                   type="submit"
                                   class="btn btn-primary btn-block">Register Now
                               </button>
                               <p 
                                   class="text-center">Have already an account <router-link to="/">Login here</router-link>
                               </p>
                           </div>
                       </form>
                   </div>
               </div>
           </div>
       </div>
  </layout-div>
</template>
 
<script>
import axios from 'axios';
import LayoutDiv from './LayoutDiv.vue';
 
export default {
 name: 'RegisterPage',
 components: {
   LayoutDiv,
 },
 data() {
   return {
       name:'',
       email:'',
       password:'',
       confirmPassword:'',
       validationErrors:{},
       isSubmitting:false,
   };
 },
 created() {
   if(localStorage.getItem('token') != "" && localStorage.getItem('token') != null){
       this.$router.push('/dashboard')
   }
 },
 methods: {
    registerAction(){
       this.isSubmitting = true
       let payload = {
           name:this.name,
           email: this.email,
           password: this.password,
           password_confirm: this.confirmPassword
       }
       axios.post('http://localhost:8000/api/v1/register', payload)
         .then(response => {
           localStorage.setItem('token', response.data.token)
           this.$router.push('/dashboard')
           return response
         })
         .catch(error => {
           this.isSubmitting = false
           if (error.response.data.errors != undefined) {
               this.validationErrors = error.response.data.errors
           }
           return error
         });
    }
 },
};
</script>
